<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="UseCommands"
    nsURI="UseCommands" nsPrefix="UseCommands">
  <eClassifiers xsi:type="ecore:EClass" name="TestSuite">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="testCase" ordered="false"
        upperBound="-1" eType="#//TestCase" containment="true" eOpposite="#//TestCase/testSuite"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TestCase">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="number" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="commands" ordered="false"
        upperBound="-1" eType="#//Commands" containment="true" eOpposite="#//Commands/testCase"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="testSuite" ordered="false"
        eType="#//TestSuite" eOpposite="#//TestSuite/testCase"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Commands">
    <eStructuralFeatures xsi:type="ecore:EReference" name="command" ordered="false"
        upperBound="-1" eType="#//Command" containment="true" eOpposite="#//Command/commands"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="testCase" ordered="false"
        eType="#//TestCase" eOpposite="#//TestCase/commands"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Command" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="commands" ordered="false"
        eType="#//Commands" eOpposite="#//Commands/command"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CreateObjectCmd" eSuperTypes="#//Command">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="obj" ordered="false" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" ordered="false" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DestroyObjectCmd" eSuperTypes="#//Command">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="obj" ordered="false" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SetAttributeCmd" eSuperTypes="#//Command">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="obj" ordered="false" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="attributeName" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GetAttributeCmd" eSuperTypes="#//Command">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="obj" ordered="false" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="attributeName" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InsertAssociationCmd" eSuperTypes="#//Command">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="obj1" ordered="false" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="obj2" ordered="false" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="association" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DeleteAssociationCmd" eSuperTypes="#//Command">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="obj1" ordered="false" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="obj2" ordered="false" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="association" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OpenterCmd" eSuperTypes="#//Command">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="obj" ordered="false" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="methodName" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="parameter" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OpexitCmd" eSuperTypes="#//Command">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
